packages:
  - "."

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: false
  sharp: true
  unrs-resolver: true
  vue-demi: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
